//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("70dba902-6081-4c92-b483-eb7ffb06b131")]
[assembly: AssemblyTitle("SolrNet.SchemaDSL")]
[assembly: AssemblyDescription("SolrNet.SchemaDSL")]
[assembly: AssemblyProduct("SolrNet.SchemaDSL")]
[assembly: AssemblyCopyright("Copyright © Studio Pešec, Matej Skubic")]
[assembly: AssemblyVersion("0.3.0")]
[assembly: AssemblyFileVersion("0.3.0")]

